//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IDepartmentTestWebService")]
public interface IDepartmentTestWebService
{
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITestWebServiceOf_Department/Insert", ReplyAction = "http://tempuri.org/ITestWebServiceOf_Department/InsertResponse")]
    [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
    void Insert(TestEFDomainAndContext.TestDomains.Department item);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITestWebServiceOf_Department/Insert", ReplyAction = "http://tempuri.org/ITestWebServiceOf_Department/InsertResponse")]
    System.Threading.Tasks.Task InsertAsync(TestEFDomainAndContext.TestDomains.Department item);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITestWebServiceOf_Department/Update", ReplyAction = "http://tempuri.org/ITestWebServiceOf_Department/UpdateResponse")]
    [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
    void Update(TestEFDomainAndContext.TestDomains.Department item);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITestWebServiceOf_Department/Update", ReplyAction = "http://tempuri.org/ITestWebServiceOf_Department/UpdateResponse")]
    System.Threading.Tasks.Task UpdateAsync(TestEFDomainAndContext.TestDomains.Department item);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITestWebServiceOf_Department/Delete", ReplyAction = "http://tempuri.org/ITestWebServiceOf_Department/DeleteResponse")]
    [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
    void Delete(TestEFDomainAndContext.TestDomains.Department item);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITestWebServiceOf_Department/Delete", ReplyAction = "http://tempuri.org/ITestWebServiceOf_Department/DeleteResponse")]
    System.Threading.Tasks.Task DeleteAsync(TestEFDomainAndContext.TestDomains.Department item);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDepartmentTestWebServiceChannel : IDepartmentTestWebService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DepartmentTestWebServiceClient : System.ServiceModel.ClientBase<IDepartmentTestWebService>, IDepartmentTestWebService
{

    public DepartmentTestWebServiceClient()
    {
    }

    public DepartmentTestWebServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public DepartmentTestWebServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public DepartmentTestWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public DepartmentTestWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public void Insert(TestEFDomainAndContext.TestDomains.Department item)
    {
        base.Channel.Insert(item);
    }

    public System.Threading.Tasks.Task InsertAsync(TestEFDomainAndContext.TestDomains.Department item)
    {
        return base.Channel.InsertAsync(item);
    }

    public void Update(TestEFDomainAndContext.TestDomains.Department item)
    {
        base.Channel.Update(item);
    }

    public System.Threading.Tasks.Task UpdateAsync(TestEFDomainAndContext.TestDomains.Department item)
    {
        return base.Channel.UpdateAsync(item);
    }

    public void Delete(TestEFDomainAndContext.TestDomains.Department item)
    {
        base.Channel.Delete(item);
    }

    public System.Threading.Tasks.Task DeleteAsync(TestEFDomainAndContext.TestDomains.Department item)
    {
        return base.Channel.DeleteAsync(item);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IEmployeeTestWebService")]
public interface IEmployeeTestWebService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITestWebServiceOf_Employee/Insert", ReplyAction = "http://tempuri.org/ITestWebServiceOf_Employee/InsertResponse")]
    [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
    void Insert(TestEFDomainAndContext.TestDomains.Employee item);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITestWebServiceOf_Employee/Insert", ReplyAction = "http://tempuri.org/ITestWebServiceOf_Employee/InsertResponse")]
    System.Threading.Tasks.Task InsertAsync(TestEFDomainAndContext.TestDomains.Employee item);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITestWebServiceOf_Employee/Update", ReplyAction = "http://tempuri.org/ITestWebServiceOf_Employee/UpdateResponse")]
    [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
    void Update(TestEFDomainAndContext.TestDomains.Employee item);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITestWebServiceOf_Employee/Update", ReplyAction = "http://tempuri.org/ITestWebServiceOf_Employee/UpdateResponse")]
    System.Threading.Tasks.Task UpdateAsync(TestEFDomainAndContext.TestDomains.Employee item);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITestWebServiceOf_Employee/Delete", ReplyAction = "http://tempuri.org/ITestWebServiceOf_Employee/DeleteResponse")]
    [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
    void Delete(TestEFDomainAndContext.TestDomains.Employee item);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITestWebServiceOf_Employee/Delete", ReplyAction = "http://tempuri.org/ITestWebServiceOf_Employee/DeleteResponse")]
    System.Threading.Tasks.Task DeleteAsync(TestEFDomainAndContext.TestDomains.Employee item);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IEmployeeTestWebServiceChannel : IEmployeeTestWebService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class EmployeeTestWebServiceClient : System.ServiceModel.ClientBase<IEmployeeTestWebService>, IEmployeeTestWebService
{

    public EmployeeTestWebServiceClient()
    {
    }

    public EmployeeTestWebServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public EmployeeTestWebServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public EmployeeTestWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public EmployeeTestWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public void Insert(TestEFDomainAndContext.TestDomains.Employee item)
    {
        base.Channel.Insert(item);
    }

    public System.Threading.Tasks.Task InsertAsync(TestEFDomainAndContext.TestDomains.Employee item)
    {
        return base.Channel.InsertAsync(item);
    }

    public void Update(TestEFDomainAndContext.TestDomains.Employee item)
    {
        base.Channel.Update(item);
    }

    public System.Threading.Tasks.Task UpdateAsync(TestEFDomainAndContext.TestDomains.Employee item)
    {
        return base.Channel.UpdateAsync(item);
    }

    public void Delete(TestEFDomainAndContext.TestDomains.Employee item)
    {
        base.Channel.Delete(item);
    }

    public System.Threading.Tasks.Task DeleteAsync(TestEFDomainAndContext.TestDomains.Employee item)
    {
        return base.Channel.DeleteAsync(item);
    }
}
